### PR TITLE
M2 Submission

### PR DESCRIPTION
**Pull request by leoMurtha**
This pull request contains:

- Changes to the API design
- API backend in Django and using PostgreSQL
- Deployment files
- It is already hosted on a cloud machine just use the links provided at the readme

### CODE REVIEW

**Comment by SofieLovdal** [comment]
Hey! Feedback for the M2 submission:

-In general, very nice job: especially nice with cloud hosting. This should count as an extra feature if I am not mistaken.
-API doc is well updated
-As far as I can see, PUT/POST for statistics is not yet fully implemented. Don't forget implementing this for M3.
-Add error messages so that the user gets a good indication of what went wrong in case a non-successful HTTP status code is returned.
-Add architectural overview of the application for M3 to the report

Good luck with implementing the M3 parts!

Sofie

**Comment by leoMurtha** [comment]
> Hey! Feedback for the M2 submission:
> 
> -In general, very nice job: especially nice with cloud hosting. This should count as an extra feature if I am not mistaken.
> -API doc is well updated
> -As far as I can see, PUT/POST for statistics is not yet fully implemented. Don't forget implementing this for M3.
> -Add error messages so that the user gets a good indication of what went wrong in case a non-successful HTTP status code is returned.
> -Add architectural overview of the application for M3 to the report
> 
> Good luck with implementing the M3 parts!
> 
> Sofie

Hey Sofie, how are you?

## PUT/POST
The PUT/POST are indeed implemented because we used the own API to feed the database, you can modify or insert new statistics via **/api/statistics**.

## Overview
We did some overview of the web app architecture but it is in an another markdown file called **Report.md**

**Comment by SofieLovdal** [comment]
Hey! Thanks for your reply.

-I can't seem to access api/statistics. /airports and /carriers works fine, but /statistics just loads infinitely. Perhaps this is why I could not find the PUT/POST option yesterday when grading (I see it now when accessing e.g. http://trvl.hopto.org:8000/api/statistics/1/. However, "/1" is not quite descriptive. Try to find a better URI for this resource, perhaps by using query parameters. (If you don't want to change it at this late stage I can understand, but it might be a small deduction). Also consider returning HTTP 201/204 in this case depending on what the server does with the request.
-I reviewed your report, and try to extend it a bit. You do not have to repeat the API design, since this is already in a separate document of course, but give an overview of your architectural design. This would include e.g. a module diagram, what technologies you used and why, and other design choices. Also describe extras that you implemented. Screenshots and other images are welcome. The most important thing would be for us to as quickly understand how you chose to implement your project and how you designed it (on an architectural level).

**Comment by SofieLovdal** [comment]
Regarding not getting statistics to load, it is not a huge issue right now, but you have to make sure it works during the demo.

**Comment by leoMurtha** [comment]
> Regarding not getting statistics to load, it is not a huge issue right now, but you have to make sure that the endpoints you want to present work during the demo.

Yes, I'm aware of the /statistics the problem is that is trying to retrieve all the entries from the database I'm gonna see if it is possible to only retrieve a few of the entries.

Thanks for the feedback :+1:

**Pull request merged**
